# Basic options
title: Neuroscience, Engineering, and Data Analysis
author: Hector D Orozco 
email: hector@neurohazardous.com
description: A project compilation 
twitter_username: neurohazardous
github_username: neurohazardous

# Build settings
markdown: kramdown
theme: jekyll-theme-minimal
