# Basic options
title: Neuroscience, Engineering, and Data Analysis Portfolio
author: Hector D Orozco 
email: hector@neurohazardous.com
description: A project compilation by Hector D Orozco
twitter_username: neurohazardous
github_username: neurohazardous
logo: img/portfolio_logo.png

# Build settings
markdown: kramdown
theme: jekyll-theme-minimal
